# Generated by Django 4.1.13 on 2025-04-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='updated_at',
        ),
    ]
