# Generated by Django 4.1.13 on 2025-04-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_loginactivity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginactivity',
            table='LoginActivity',
        ),
    ]
