# Generated by Django 4.1.13 on 2025-04-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agencyserviceauthorization'),
        ('account', '0006_alter_loginactivity_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.agency'),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.branch'),
        ),
    ]
