# Generated by Django 4.1.13 on 2025-03-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.IntegerField()),
                ('product_code', models.CharField(max_length=50)),
                ('service_id', models.IntegerField()),
                ('agency_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('request_data', models.TextField()),
                ('response_data', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servis Logu',
                'verbose_name_plural': 'Servis Logları',
                'db_table': 'proposalservicelog',
            },
        ),
        migrations.CreateModel(
            name='UavtDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.IntegerField()),
                ('product_code', models.CharField(max_length=50)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('agency_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('uavt_code', models.CharField(max_length=20, unique=True)),
                ('il_kodu', models.CharField(blank=True, max_length=10, null=True)),
                ('ilce_kodu', models.CharField(blank=True, max_length=10, null=True)),
                ('koy_kodu', models.CharField(blank=True, max_length=10, null=True)),
                ('mahalle_kodu', models.CharField(blank=True, max_length=10, null=True)),
                ('csbm_kodu', models.CharField(blank=True, max_length=10, null=True)),
                ('bina_kodu', models.CharField(blank=True, max_length=20, null=True)),
                ('bina_adi', models.CharField(blank=True, max_length=255, null=True)),
                ('daire_kodu', models.CharField(blank=True, max_length=20, null=True)),
                ('daire_numarasi', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UAVT Detayı',
                'verbose_name_plural': 'UAVT Detayları',
                'db_table': 'uavtdetails',
            },
        ),
    ]
