# Generated by Django 4.1.13 on 2025-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_proposalservicelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavtdetails',
            name='daire_metrekare',
            field=models.CharField(blank=True, db_column='daire_metrekare', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='dask_hasar_durumu',
            field=models.CharField(blank=True, db_column='dask_hasar_durumu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='dask_insa_yili',
            field=models.CharField(blank=True, db_column='dask_insa_yili', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='dask_kat_araligi',
            field=models.CharField(blank=True, db_column='dask_kat_araligi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='dask_kullanim_sekli',
            field=models.CharField(blank=True, db_column='dask_kullanim_sekli', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='dask_yapi_tarzi',
            field=models.CharField(blank=True, db_column='dask_yapi_tarzi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='sigorta_ettiren_sifati',
            field=models.CharField(blank=True, db_column='sigorta_ettiren_sifati', max_length=100, null=True),
        ),
    ]
