# Generated by Django 4.1.13 on 2025-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_uavtdetails_daire_metrekare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavtdetails',
            name='riziko_ada',
            field=models.CharField(blank=True, db_column='riziko_ada', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='riziko_konum',
            field=models.CharField(blank=True, db_column='riziko_konum', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='riziko_pafta',
            field=models.CharField(blank=True, db_column='riziko_pafta', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='riziko_parsel',
            field=models.CharField(blank=True, db_column='riziko_parsel', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='riziko_tipi',
            field=models.CharField(blank=True, db_column='riziko_tipi', max_length=100, null=True),
        ),
    ]
