# Generated by Django 4.1.13 on 2025-05-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_companyparametermapping'),
        ('gateway', '0004_uavtdetails_riziko_ada_uavtdetails_riziko_konum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalservicelog',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.offerserviceconfiguration'),
        ),
    ]
