# Generated by Django 4.1.13 on 2025-05-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_companyparametermapping'),
        ('gateway', '0005_alter_proposalservicelog_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalservicelog',
            name='service',
        ),
        migrations.AddField(
            model_name='proposalservicelog',
            name='info_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.serviceconfiguration'),
        ),
        migrations.AddField(
            model_name='proposalservicelog',
            name='offer_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.offerserviceconfiguration'),
        ),
        migrations.AlterField(
            model_name='proposalservicelog',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proposalservicelog',
            name='proposal_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
