# Generated by Django 4.1.13 on 2025-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_remove_proposalservicelog_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalservicelog',
            name='sub_product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
