# Generated by Django 4.1.13 on 2025-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_proposalservicelog_sub_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavtdetails',
            name='acik_adres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='il_adi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uavtdetails',
            name='ilce_adi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
