# Generated by Django 4.1.13 on 2025-05-15 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import offer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0025_insurancecompany_parser_function'),
        ('agency', '0004_agencyofferserviceauthorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferFixedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('key_id', models.IntegerField()),
                ('value', models.FloatField()),
                ('multiply_with_key_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proposal_id', models.BigIntegerField(unique=True)),
                ('uuid', models.CharField(default=offer.models.generate_uuid, editable=False, max_length=36, unique=True)),
                ('form_type', models.CharField(max_length=50)),
                ('product_code', models.IntegerField()),
                ('status', models.CharField(default='completed', max_length=20)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('property_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('property_info', models.JSONField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.customer')),
                ('policy_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.policybranch')),
            ],
            options={
                'db_table': 'proposal',
            },
        ),
        migrations.CreateModel(
            name='ProposalUUIDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=offer.models.generate_uuid, editable=False, max_length=36, unique=True)),
                ('proposal_id', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proposal_uuid_mapping',
            },
        ),
        migrations.CreateModel(
            name='ProposalDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proposal_code', models.BigIntegerField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=50)),
                ('sub_product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('gross_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('offer_number', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization_detail', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='TRY', max_length=10)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.agency')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offer.proposal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposaldetails',
            },
        ),
        migrations.CreateModel(
            name='DaskMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(max_length=100)),
                ('company_value', models.CharField(max_length=50)),
                ('key_id', models.IntegerField()),
                ('parameter_id', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.serviceconfiguration')),
            ],
            options={
                'db_table': 'dask_mapping',
            },
        ),
        migrations.CreateModel(
            name='CustomerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(db_index=True, max_length=11)),
                ('customer_no', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Customer Company',
                'verbose_name_plural': 'Customer Companies',
                'db_table': 'customer_company',
            },
        ),
        migrations.CreateModel(
            name='ProposalKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('key_id', models.IntegerField()),
                ('key_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.agency')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teklif Key Bilgisi',
                'verbose_name_plural': 'Teklif Key Bilgileri',
                'db_table': 'proposalkeys',
                'unique_together': {('proposal_id', 'product_code', 'key_id')},
            },
        ),
        migrations.AddIndex(
            model_name='proposaldetails',
            index=models.Index(fields=['proposal'], name='proposaldet_proposa_5449f5_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaldetails',
            index=models.Index(fields=['insurance_company'], name='proposaldet_insuran_286799_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaldetails',
            index=models.Index(fields=['product_code'], name='proposaldet_product_80958e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='daskmapping',
            unique_together={('service', 'service_key', 'company_value', 'key_id')},
        ),
        migrations.AlterUniqueTogether(
            name='customercompany',
            unique_together={('identity_number', 'company')},
        ),
    ]
