# Generated by Django 4.1.13 on 2025-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaldetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('timeout', 'Zaman Aşımı')], default='pending', max_length=50),
        ),
    ]
