# Generated by Django 4.1.13 on 2025-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_proposal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
