# Generated by Django 4.1.13 on 2025-07-20 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_proposal_is_deleted_proposal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='parent_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_proposals', to='offer.proposal'),
        ),
    ]
