# Generated by Django 4.1.13 on 2025-07-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0083_remove_offerserviceconfiguration_token_password_and_more'),
        ('offer', '0006_proposal_parent_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRevisableKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50)),
                ('sub_product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('target_company_key', models.CharField(max_length=255)),
                ('template_variable', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.key')),
            ],
            options={
                'db_table': 'company_revisable_keys',
                'unique_together': {('insurance_company', 'product_code', 'key', 'target_company_key')},
            },
        ),
    ]
