# Generated by Django 4.1.13 on 2025-06-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0051_collection_komisyonorannet'),
        ('agency', '0006_alter_agency_id_alter_agencycompany_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('block_start', models.DateField()),
                ('block_end', models.DateField()),
                ('total_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('request_sent', models.BooleanField(default=False)),
                ('response_received', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Transfer Log',
                'verbose_name_plural': 'Transfer Logları',
                'db_table': 'transfer_log',
            },
        ),
        migrations.CreateModel(
            name='TransferLogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('created', 'Oluşturuldu'), ('updated', 'Güncellendi'), ('skipped', 'Atlandı'), ('failed', 'Hatalı')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transfer.transferlog')),
            ],
            options={
                'verbose_name': 'Transfer Poliçe Log Detayı',
                'verbose_name_plural': 'Transfer Poliçe Log Detayları',
                'db_table': 'transfer_log_detail',
            },
        ),
    ]
