# Generated by Django 4.1.13 on 2025-06-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTransferTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_no', models.CharField(db_index=True, max_length=50)),
                ('zeyil_no', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('yenileme_no', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('tanzim_tarihi', models.DateField(blank=True, null=True)),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_id', models.IntegerField(db_index=True)),
                ('TahsilatTahakkuk', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Geçici Poliçe Transferi',
                'verbose_name_plural': 'Geçici Poliçe Transferleri',
                'db_table': 'policy_transfer_temp',
                'unique_together': {('police_no', 'zeyil_no', 'yenileme_no', 'batch_id', 'agency_id')},
            },
        ),
    ]
