# Generated by Django 4.1.13 on 2025-06-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_policytransfertemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytransfertemp',
            name='company_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='policytransfertemp',
            name='service_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='policytransfertemp',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
