# Generated by Django 4.1.13 on 2025-06-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_policytransfertemp_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policytransfertemp',
            old_name='police_no',
            new_name='PoliceNo',
        ),
        migrations.RenameField(
            model_name='policytransfertemp',
            old_name='tanzim_tarihi',
            new_name='PoliceTanzimTarihi',
        ),
        migrations.RenameField(
            model_name='policytransfertemp',
            old_name='yenileme_no',
            new_name='YenilemeNo',
        ),
        migrations.RenameField(
            model_name='policytransfertemp',
            old_name='zeyil_no',
            new_name='ZeyilNo',
        ),
        migrations.AlterUniqueTogether(
            name='policytransfertemp',
            unique_together={('PoliceNo', 'ZeyilNo', 'YenilemeNo', 'batch_id', 'agency_id')},
        ),
    ]
