# Generated by Django 4.1.13 on 2025-06-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_rename_police_no_policytransfertemp_policeno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytransfertemp',
            name='SirketUrunNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
