# Generated by Django 4.1.13 on 2025-06-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_assethome_dainimurtehinadi_assethome_daskbitistarihi_and_more'),
        ('transfer', '0005_policytransfertemp_sirketurunno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(db_index=True, max_length=20)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Döviz Eşlemesi',
                'verbose_name_plural': 'Döviz Eşlemeleri',
                'db_table': 'currency_mapping',
                'unique_together': {('company', 'raw_value')},
            },
        ),
    ]
