# Generated by Django 4.1.13 on 2025-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_currencymapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencymapping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
