# Generated by Django 4.1.13 on 2025-06-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0008_alter_policytransfertemp_id_alter_transferlog_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferlog',
            options={},
        ),
        migrations.RenameField(
            model_name='transferlog',
            old_name='updated_count',
            new_name='cars_created',
        ),
        migrations.AddField(
            model_name='transferlog',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='customers_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='homes_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuel'), ('auto', 'Zamanlanmış'), ('api', 'API')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='transferlog',
            table=None,
        ),
    ]
