# Generated by Django 4.1.13 on 2025-06-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0069_alter_assetcars_aracrenk'),
        ('transfer', '0009_alter_transferlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlogdetail',
            name='customer_identity_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='transferlogdetail',
            name='data_source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transferlogdetail',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferlogdetail',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.policy'),
        ),
        migrations.AddField(
            model_name='transferlogdetail',
            name='record_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
