# Generated by Django 4.1.13 on 2025-06-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_transferlogdetail_customer_identity_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPostProcessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_verified_count', models.IntegerField(default=0)),
                ('cars_verified_count', models.IntegerField(default=0)),
                ('homes_verified_count', models.IntegerField(default=0)),
                ('cars_traffic_potential', models.IntegerField(default=0)),
                ('cars_kasko_potential', models.IntegerField(default=0)),
                ('homes_dask_potential', models.IntegerField(default=0)),
                ('homes_konut_potential', models.IntegerField(default=0)),
                ('digital_customer_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postprocess_logs', to='transfer.transferlog')),
            ],
            options={
                'verbose_name': 'Transfer Sonrası İşlem Logu',
                'verbose_name_plural': 'Transfer Sonrası İşlem Logları',
                'db_table': 'transfer_postprocess_log',
            },
        ),
    ]
