# Generated by Django 4.1.13 on 2025-06-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_transferpostprocesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferpostprocesslog',
            name='certificate_found_count',
            field=models.IntegerField(default=0),
        ),
    ]
