# Generated by Django 4.1.13 on 2025-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_transferpostprocesslog_certificate_found_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlog',
            name='updated_count',
            field=models.IntegerField(default=0),
        ),
    ]
