# Generated by Django 5.1.7 on 2025-03-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sigorta Şirketi',
                'verbose_name_plural': 'Sigorta Şirketleri',
                'db_table': 'insurancecompany',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('KeyID', models.AutoField(primary_key=True, serialize=False)),
                ('KeyName', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('DeletedDate', models.DateTimeField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('InputType', models.CharField(max_length=50, null=True)),
                ('MinLength', models.IntegerField(blank=True, null=True)),
                ('MaxLength', models.IntegerField(blank=True, null=True)),
                ('RegexPattern', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'keys',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('ParameterID', models.AutoField(primary_key=True, serialize=False)),
                ('ParameterName', models.CharField(max_length=100)),
                ('DefaultValue', models.CharField(blank=True, max_length=255, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=100, verbose_name='Şirket Kodu')),
                ('urun_kod', models.CharField(max_length=100, unique=True, verbose_name='Ürün Kodu')),
                ('urun_adi', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('anabrans_id', models.IntegerField(verbose_name='Ana Branş ID')),
                ('altbrans_id', models.IntegerField(verbose_name='Alt Branş ID')),
                ('sirket_kod', models.CharField(max_length=100, verbose_name='Şirket Kodu')),
                ('sirket_adi', models.CharField(max_length=255, verbose_name='Şirket Adı')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('soap_action', models.CharField(max_length=255)),
                ('soap_template', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_configurations', to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Servis Yapılandırması',
                'verbose_name_plural': 'Servis Yapılandırmaları',
                'db_table': 'serviceconfigurations',
            },
        ),
        migrations.CreateModel(
            name='KeyParameters',
            fields=[
                ('KeyParameterID', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('KeyID', models.ForeignKey(db_column='KeyID', on_delete=django.db.models.deletion.CASCADE, to='database.key')),
                ('ParameterID', models.ForeignKey(db_column='ParameterID', on_delete=django.db.models.deletion.CASCADE, to='database.parameter')),
            ],
            options={
                'db_table': 'keyparameters',
                'unique_together': {('KeyID', 'ParameterID')},
            },
        ),
    ]
