# Generated by Django 4.1.13 on 2025-03-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_serviceconfiguration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='FormBlock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='OrderIndex',
            field=models.IntegerField(default=0),
        ),
    ]
