# Generated by Django 4.1.13 on 2025-03-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_key_formblock_key_orderindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='FormBlock',
        ),
        migrations.RemoveField(
            model_name='key',
            name='OrderIndex',
        ),
    ]
