# Generated by Django 4.1.13 on 2025-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_key_formblock_remove_key_orderindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='VisibleIfKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='VisibleIfValue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='InputType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
