# Generated by Django 4.1.13 on 2025-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_key_visibleifkey_key_visibleifvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityCode', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'City',
            },
        ),
    ]
