# Generated by Django 4.1.13 on 2025-04-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='dask_phone',
            field=models.CharField(blank=True, db_column='dask_phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_phone',
            field=models.CharField(blank=True, db_column='secondary_phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='transfer_phone',
            field=models.CharField(blank=True, db_column='transfer_phone', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_customers', to='database.customer')),
                ('relationship_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.relationshiptype')),
                ('to_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='database.customer')),
            ],
            options={
                'unique_together': {('from_customer', 'to_customer', 'relationship_type')},
            },
        ),
    ]
