# Generated by Django 4.1.13 on 2025-04-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_relationshiptype_customer_dask_phone_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrelationship',
            options={'verbose_name': 'Customer Relationship', 'verbose_name_plural': 'Customer Relationships'},
        ),
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'verbose_name': 'Relationship Type', 'verbose_name_plural': 'Relationship Types'},
        ),
        migrations.AlterModelTable(
            name='customerrelationship',
            table='customer_relationships',
        ),
        migrations.AlterModelTable(
            name='relationshiptype',
            table='relationship_types',
        ),
    ]
