# Generated by Django 4.1.13 on 2025-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_customerrelationship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='applicable_to',
            field=models.CharField(choices=[('individual_to_individual', 'Bireysel → Bireysel'), ('individual_to_corporate', 'Bireysel → Tüzel'), ('corporate_to_individual', 'Tüzel → Bireysel'), ('corporate_to_corporate', 'Tüzel → Tüzel')], default='individual_to_individual', max_length=30),
        ),
    ]
