# Generated by Django 4.1.13 on 2025-04-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_relationshiptype_applicable_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerrelationship',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customerrelationship',
            constraint=models.UniqueConstraint(fields=('from_customer', 'to_customer', 'relationship_type'), name='unique_customer_relationship'),
        ),
    ]
