# Generated by Django 4.1.13 on 2025-04-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_customerrelationship_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=True),
        ),
    ]
