# Generated by Django 4.1.13 on 2025-04-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_customer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='reverse_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
