# Generated by Django 4.1.13 on 2025-04-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_relationshiptype_reverse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyMainBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Poliçe Ana Branş',
                'verbose_name_plural': 'Poliçe Ana Branşlar',
                'db_table': 'policy_main_branch',
            },
        ),
        migrations.CreateModel(
            name='PolicyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(unique=True)),
                ('main_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.policymainbranch')),
            ],
            options={
                'verbose_name': 'Poliçe Branşı',
                'verbose_name_plural': 'Poliçe Branşları',
                'db_table': 'policy_branch',
            },
        ),
    ]
