# Generated by Django 4.1.13 on 2025-04-16 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_policymainbranch_policybranch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='urun_kod',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='urun_adi',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='altbrans_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='anabrans_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sirket_adi',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sirket_kod',
        ),
        migrations.AddField(
            model_name='products',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.policybranch', verbose_name='Alt Branş'),
        ),
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany', verbose_name='Sigorta Şirketi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='main_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.policymainbranch', verbose_name='Ana Branş'),
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
