# Generated by Django 4.1.13 on 2025-04-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_rename_urun_kod_products_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_1',
            field=models.CharField(blank=True, db_column='phone_1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, db_column='phone_2', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_3',
            field=models.CharField(blank=True, db_column='phone_3', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='transfer_email',
            field=models.EmailField(blank=True, db_column='transfer_email', max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
