# Generated by Django 4.1.13 on 2025-04-24 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_agencyserviceauthorization_is_active'),
        ('database', '0016_customer_phone_1_customer_phone_2_customer_phone_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='agency.branch'),
        ),
    ]
