# Generated by Django 4.1.13 on 2025-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_customer_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Ürün Kodu'),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('company', 'code')},
        ),
    ]
