# Generated by Django 4.1.13 on 2025-04-26 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0018_alter_products_code_alter_products_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('policy_number', models.CharField(max_length=50)),
                ('endorsement_number', models.CharField(blank=True, max_length=20, null=True)),
                ('renewal_number', models.CharField(blank=True, max_length=20, null=True)),
                ('combined_policy_number', models.CharField(editable=False, max_length=100)),
                ('endorsement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dask_policy_no', models.CharField(blank=True, max_length=100, null=True)),
                ('uavt_code', models.CharField(blank=True, max_length=50, null=True)),
                ('square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('net_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='database.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='database.products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
            },
        ),
    ]
