# Generated by Django 4.1.13 on 2025-04-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verified_status',
            field=models.CharField(choices=[('0', 'Not Verified'), ('1', 'Verified')], db_column='verified_status', default='0', max_length=1),
        ),
    ]
