# Generated by Django 4.1.13 on 2025-05-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_customer_verified_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=50)),
                ('sub_product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_product_description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('soap_action', models.CharField(max_length=255)),
                ('soap_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_services', to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Teklif Servisi',
                'verbose_name_plural': 'Teklif Servisleri',
                'db_table': 'offer_service_configurations',
            },
        ),
    ]
