# Generated by Django 4.1.13 on 2025-05-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_offerserviceconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyParameterMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50)),
                ('target_company_key', models.CharField(blank=True, max_length=255, null=True)),
                ('company_parameter', models.CharField(blank=True, max_length=255, null=True)),
                ('company_parameter_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.key')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.parameter')),
            ],
            options={
                'db_table': 'company_parameter_mappings',
                'unique_together': {('insurance_company', 'product_code', 'key', 'parameter')},
            },
        ),
    ]
