# Generated by Django 4.1.13 on 2025-05-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_companyparametermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='auth_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='auth_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='custom_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='requires_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='auth_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='auth_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='custom_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='requires_auth',
            field=models.BooleanField(default=False),
        ),
    ]
