# Generated by Django 4.1.13 on 2025-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_offerserviceconfiguration_auth_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='content_type',
            field=models.CharField(default='application/json', max_length=50),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='is_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='request_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='token_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='token_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='token_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='content_type',
            field=models.CharField(default='application/json', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='is_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='request_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='token_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='token_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='token_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offerserviceconfiguration',
            name='soap_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offerserviceconfiguration',
            name='soap_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='soap_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
