# Generated by Django 4.1.13 on 2025-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_offerserviceconfiguration_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='parser_function',
            field=models.CharField(blank=True, help_text='Yanıtları işlemek için kullanılacak parser fonksiyon adı', max_length=100, null=True),
        ),
    ]
