# Generated by Django 4.1.13 on 2025-05-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_insurancecompany_parser_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='pdf_field_path',
            field=models.CharField(blank=True, help_text='Cevapta PDF verisinin bulunduğu path (XML veya JSON key, ör: .//Base64)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceconfiguration',
            name='response_type',
            field=models.CharField(choices=[('url', 'URL'), ('base64', 'Base64'), ('bytes', 'Bytes/Binary')], default='url', help_text='Servis PDF çıktısı hangi formatta döner? Örn: url, base64, bytes', max_length=20),
        ),
    ]
