# Generated by Django 4.1.13 on 2025-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_serviceconfiguration_pdf_field_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='error_field_path',
            field=models.CharField(blank=True, help_text='Hata/uyarı mesajı XML veya JSON key path (ör: .//Message, .//faultstring)', max_length=255, null=True),
        ),
    ]
