# Generated by Django 4.1.13 on 2025-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_serviceconfiguration_error_field_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(unique=True)),
                ('country_name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Travel Country',
                'verbose_name_plural': 'Travel Countries',
                'db_table': 'travel_country',
            },
        ),
    ]
