# Generated by Django 4.1.13 on 2025-05-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_travelcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_field', models.CharField(help_text='Dönüşteki alanın adı/yolu (örn: modelYear, stats.YKT, informations.15)', max_length=100)),
                ('parse_type', models.CharField(choices=[('field', 'Field'), ('dict', 'DictField'), ('xpath', 'XPath'), ('jsonpath', 'JsonPath')], default='field', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.ForeignKey(blank=True, help_text="Değer doğrudan bu key'e yazılır.", null=True, on_delete=django.db.models.deletion.CASCADE, to='database.key')),
                ('parameter', models.ForeignKey(blank=True, help_text="Eğer değer bir key'in parametresi ise, burada belirtilir.", null=True, on_delete=django.db.models.deletion.CASCADE, to='database.parameter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='database.serviceconfiguration')),
            ],
            options={
                'verbose_name': 'Servis Field Mapping',
                'verbose_name_plural': 'Servis Field Mappings',
                'db_table': 'service_field_mappings',
                'unique_together': {('service', 'response_field', 'key', 'parameter')},
            },
        ),
    ]
