# Generated by Django 4.1.13 on 2025-05-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_servicefieldmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefieldmapping',
            name='expected_value',
            field=models.CharField(blank=True, help_text='Gelen değerde beklenen karşılık (örn: TKL için 004, 001, vb.)', max_length=50, null=True),
        ),
    ]
