# Generated by Django 4.1.13 on 2025-05-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_servicefieldmapping_expected_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerserviceconfiguration',
            name='parser_function',
            field=models.CharField(blank=True, help_text='Yanıtları işlemek için kullanılacak parser fonksiyon adı', max_length=100, null=True),
        ),
    ]
