# Generated by Django 4.1.13 on 2025-06-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_offerserviceconfiguration_parser_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(choices=[('main', 'Birincil'), ('secondary', 'İkincil'), ('dask', 'DASK'), ('transfer', 'Transfer'), ('other', 'Diğer')], default='other', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='database.customer')),
            ],
            options={
                'verbose_name': 'Customer Contact',
                'verbose_name_plural': 'Customer Contacts',
                'db_table': 'customer_contacts',
            },
        ),
    ]
