# Generated by Django 4.1.13 on 2025-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_customercontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dask_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='transfer_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='transfer_phone',
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(fields=('customer', 'value'), name='unique_customer_contact_value'),
        ),
    ]
