# Generated by Django 4.1.13 on 2025-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_remove_customer_dask_phone_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_text',
            field=models.TextField(blank=True, db_column='address_text', null=True),
        ),
    ]
