# Generated by Django 4.1.13 on 2025-06-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_rename_is_active_policy_aktifmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='last_synced_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
