# Generated by Django 4.1.13 on 2025-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_policy_last_synced_at_policy_last_synced_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='requires_detail_service',
            field=models.BooleanField(default=True, help_text='Bu servis için detay servisine çıkılması gerekiyor mu? (True=Çıkılacak, False=Tek response ile tamam)'),
        ),
    ]
