# Generated by Django 4.1.13 on 2025-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_serviceconfiguration_requires_detail_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='policy_list_path',
            field=models.TextField(blank=True, help_text='Poliçe listesi path (birden fazla path için | ile ayır)', null=True),
        ),
    ]
