# Generated by Django 4.1.13 on 2025-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_alter_serviceconfiguration_policy_list_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_place',
            new_name='AnneAdi',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='father_name',
            new_name='BabaAdi',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='gender',
            new_name='Cinsiyet',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mother_name',
            new_name='DogumYeri',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address_code',
            new_name='MedeniDurum',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address_text',
            new_name='RizikoAcikAdres',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city_code',
            new_name='RizikoUavtKod',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nationality_code',
            new_name='Riziko_il_kod',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nationality_code2',
            new_name='Riziko_ilce_kodu',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='deceased',
            new_name='VefatTarihi',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='Uyruk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='UyrukDiger',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
