# Generated by Django 4.1.13 on 2025-06-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_rename_birth_place_customer_anneadi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfiguration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CompanyTransferFieldMapping',
        ),
    ]
