# Generated by Django 4.1.13 on 2025-06-12 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_alter_serviceconfiguration_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_key', models.CharField(help_text='Şirketten gelen XML/JSON field/yolu', max_length=100)),
                ('company_parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('company_parameter_value', models.CharField(blank=True, max_length=100, null=True)),
                ('response_field', models.CharField(blank=True, help_text='XML/JSON path veya node (örn: Policeler.Police.PoliceNo, details.1.value)', max_length=100, null=True)),
                ('parse_type', models.CharField(choices=[('field', 'Field'), ('dict', 'DictField'), ('xpath', 'XPath'), ('jsonpath', 'JsonPath')], default='field', help_text='Parse metodu: Düz alan, nested dict, XPath, JsonPath', max_length=20)),
                ('expected_value', models.CharField(blank=True, help_text="Filtre veya eşleşme için beklenen değer (örn: 'K', 'Evet')", max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='database.insurancecompany')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.key')),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.parameter')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_field_mappings', to='database.serviceconfiguration')),
            ],
            options={
                'db_table': 'company_field_mapping',
                'unique_together': {('company', 'service', 'company_key', 'company_parameter', 'company_parameter_value', 'key', 'parameter')},
            },
        ),
    ]
