# Generated by Django 4.1.13 on 2025-06-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_companyfieldmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='detail_service',
            field=models.ForeignKey(blank=True, help_text='İlk servis sonrası çıkılacak detay servis (örn: detay/lookup servisi).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_services', to='database.serviceconfiguration'),
        ),
    ]
