# Generated by Django 4.1.13 on 2025-06-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_serviceconfiguration_detail_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfiguration',
            name='has_full_detail_in_first_service',
            field=models.BooleanField(default=False, help_text='Müşteri/varlık/tahsilat gibi detaylar ilk toplu serviste geliyor mu? (True: Evet, False: Hayır)'),
        ),
    ]
