# Generated by Django 4.1.13 on 2025-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_serviceconfiguration_has_full_detail_in_first_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='PoliceAnaKey',
            field=models.CharField(db_index=True, default='', editable=False, help_text='PoliceNo-YenilemeNo kombinasyonu ile benzersiz anahtar', max_length=100),
            preserve_default=False,
        ),
    ]
