# Generated by Django 4.1.13 on 2025-06-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_policy_policeanakey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='passive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
