# Generated by Django 4.1.13 on 2025-06-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_alter_agency_id_alter_agencycompany_id_and_more'),
        ('database', '0047_alter_customercontact_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='agency.agency'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='AktifMi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
