# Generated by Django 4.1.13 on 2025-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0048_policy_agency_alter_policy_aktifmi_alter_policy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='company_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
