# Generated by Django 4.1.13 on 2025-06-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_alter_agency_id_alter_agencycompany_id_and_more'),
        ('database', '0049_policy_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='GuncelPoliceBorcu',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='TaksitDurumu',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='TaksitTipi',
        ),
        migrations.AddField(
            model_name='collection',
            name='agency',
            field=models.ForeignKey(blank=True, db_column='agency_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='agency.agency'),
        ),
        migrations.AddField(
            model_name='collection',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_by_customer', to='database.customer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='database.policy'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
