# Generated by Django 4.1.13 on 2025-06-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_remove_collection_guncelpoliceborcu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='KomisyonOranNet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
