# Generated by Django 4.1.13 on 2025-06-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0051_collection_komisyonorannet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('soap_action', models.CharField(blank=True, max_length=255, null=True)),
                ('soap_template', models.TextField(blank=True, null=True)),
                ('policy_list_path', models.TextField(blank=True, null=True)),
                ('error_field_path', models.CharField(blank=True, max_length=255, null=True)),
                ('requires_detail_service', models.BooleanField(default=True)),
                ('has_full_detail_in_first_service', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.transferserviceconfiguration')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany')),
            ],
            options={
                'db_table': 'transfer_service_configurations',
            },
        ),
    ]
