# Generated by Django 4.1.13 on 2025-06-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_transferserviceconfiguration_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='handler_function',
            field=models.CharField(blank=True, help_text='Servisi çalıştıracak Python fonksiyonunun adı', max_length=100, null=True),
        ),
    ]
