# Generated by Django 4.1.13 on 2025-06-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_alter_companyfieldmapping_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceFieldMapping',
        ),
    ]
