# Generated by Django 4.1.13 on 2025-06-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_companyservicefieldmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservicefieldmapping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
