# Generated by Django 4.1.13 on 2025-06-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0058_alter_companyservicefieldmapping_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'policy_status',
            },
        ),
    ]
