# Generated by Django 4.1.13 on 2025-06-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0059_policystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='PolicyStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.policystatus'),
        ),
    ]
