# Generated by Django 4.1.13 on 2025-06-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_agencytransferserviceauthorization_table'),
        ('database', '0060_policy_policystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentplan',
            old_name='TahsilatTahakkuk',
            new_name='Sira',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='OdemeSekli',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='PoliceOdemeKapanisTarih',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='insured',
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='agency.agency'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='database.policy'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
