# Generated by Django 4.1.13 on 2025-06-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0061_rename_tahsilattahakkuk_paymentplan_sira_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentplan',
            old_name='Sira',
            new_name='TaksitSirasi',
        ),
    ]
