# Generated by Django 4.1.13 on 2025-06-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_rename_sira_paymentplan_taksitsirasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentplan',
            old_name='PoliceVadeTarihi',
            new_name='TaksitVadeTarihi',
        ),
    ]
