# Generated by Django 4.1.13 on 2025-06-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_agencytransferserviceauthorization_table'),
        ('database', '0063_rename_policevadetarihi_paymentplan_taksitvadetarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcars',
            name='AracTescilTam',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetcars',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_assets', to='agency.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcars',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_assets', to='database.policy'),
        ),
        migrations.AddField(
            model_name='assethome',
            name='agency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='home_assets', to='agency.agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assethome',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_assets', to='database.policy'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcars',
            unique_together={('insured', 'AracSasiNo')},
        ),
        migrations.AlterUniqueTogether(
            name='assethome',
            unique_together={('insured', 'RizikoUavtKod')},
        ),
    ]
