# Generated by Django 4.1.13 on 2025-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0064_assetcars_aractesciltam_assetcars_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethome',
            name='DainiMurtehinAdi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assethome',
            name='DaskBitisTarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assethome',
            name='RehinliAlacakliVar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assethome',
            name='Riziko_koy_adi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assethome',
            name='Riziko_mahalle_adi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assethome',
            name='Riziko_sokak_adi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
