# Generated by Django 4.1.13 on 2025-06-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_assethome_is_verified_alter_assetcars_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcars',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
