# Generated by Django 4.1.13 on 2025-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0068_alter_assetcars_aracrenk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcars',
            name='AracRenk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
