# Generated by Django 4.1.13 on 2025-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0069_alter_assetcars_aracrenk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='content_type',
            field=models.CharField(default='application/json', max_length=50),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='custom_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='is_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='request_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_extra_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_grant_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_response_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_scope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='token_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
