# Generated by Django 4.1.13 on 2025-06-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0070_transferserviceconfiguration_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethome',
            name='RizikoDaireYuzOlcumu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
