# Generated by Django 4.1.13 on 2025-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0071_alter_assethome_rizikodaireyuzolcumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
