# Generated by Django 4.1.13 on 2025-06-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0072_policy_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='company_id',
        ),
        migrations.AddField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='database.insurancecompany'),
        ),
    ]
