# Generated by Django 4.1.13 on 2025-06-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0073_remove_policy_company_id_policy_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAssetRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.assetcars')),
                ('asset_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.assethome')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.policy')),
            ],
            options={
                'verbose_name': 'Poliçe Varlık İlişkisi',
                'verbose_name_plural': 'Poliçe Varlık İlişkileri',
                'db_table': 'policy_asset_relation',
            },
        ),
        migrations.AddConstraint(
            model_name='policyassetrelation',
            constraint=models.UniqueConstraint(fields=('policy', 'asset_car'), name='unique_policy_car'),
        ),
        migrations.AddConstraint(
            model_name='policyassetrelation',
            constraint=models.UniqueConstraint(fields=('policy', 'asset_home'), name='unique_policy_home'),
        ),
    ]
