# Generated by Django 4.1.13 on 2025-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0074_policyassetrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='MapCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
