# Generated by Django 4.1.13 on 2025-07-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0075_city_mapcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('agency_id', 'identity_number')},
        ),
    ]
