# Generated by Django 4.1.13 on 2025-07-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0076_alter_customer_identity_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='eventvalidation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='submit_ajax_template',
            field=models.TextField(blank=True, help_text='submitAjaxEventConfig içeriği için jinja2 template', null=True),
        ),
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='viewstate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
