# Generated by Django 4.1.13 on 2025-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0077_transferserviceconfiguration_eventvalidation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferserviceconfiguration',
            name='has_credit_card_service',
            field=models.BooleanField(default=True, help_text='Kredi kartı servisi varsa True'),
        ),
    ]
