# Generated by Django 4.1.13 on 2025-07-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0078_transferserviceconfiguration_has_credit_card_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='has_credit_card_service',
        ),
    ]
