# Generated by Django 4.1.13 on 2025-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0079_remove_transferserviceconfiguration_has_credit_card_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='has_credit_card_task',
            field=models.BooleanField(default=False, help_text='Bu şirketin kredi kartı servisi Celery task ile ayrı çalışır'),
        ),
    ]
