# Generated by Django 4.1.13 on 2025-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0080_insurancecompany_has_credit_card_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='credit_card_handler_function',
            field=models.CharField(blank=True, help_text="Kredi kartı task'ını tetikleyecek fonksiyon adı", max_length=100, null=True),
        ),
    ]
