# Generated by Django 4.1.13 on 2025-07-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0081_insurancecompany_credit_card_handler_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceconfiguration',
            name='token_password',
        ),
        migrations.RemoveField(
            model_name='serviceconfiguration',
            name='token_url',
        ),
        migrations.RemoveField(
            model_name='serviceconfiguration',
            name='token_username',
        ),
    ]
