# Generated by Django 4.1.13 on 2025-07-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0082_remove_serviceconfiguration_token_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerserviceconfiguration',
            name='token_password',
        ),
        migrations.RemoveField(
            model_name='offerserviceconfiguration',
            name='token_url',
        ),
        migrations.RemoveField(
            model_name='offerserviceconfiguration',
            name='token_username',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='custom_headers',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_client_id',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_client_secret',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_extra_params',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_grant_type',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_password',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_response_path',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_scope',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_url',
        ),
        migrations.RemoveField(
            model_name='transferserviceconfiguration',
            name='token_username',
        ),
    ]
