# Generated by Django 4.1.13 on 2025-07-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0083_remove_offerserviceconfiguration_token_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservicefieldmapping',
            name='company_key',
            field=models.CharField(help_text='Şirketten gelen XML/JSON field/yolu', max_length=255),
        ),
    ]
