# Generated by Django 4.1.13 on 2025-07-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0084_alter_companyservicefieldmapping_company_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policybranch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policymainbranch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
