# Generated by Django 4.1.13 on 2025-07-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_agencypasswords_kaynak_kod_agencypasswords_sube_kod'),
        ('database', '0085_alter_policybranch_id_alter_policymainbranch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTramerPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcentePartajNo', models.CharField(blank=True, max_length=20, null=True)),
                ('PoliceTanzimTarihi', models.DateTimeField(blank=True, null=True)),
                ('PoliceBaslangicTarihi', models.DateTimeField(blank=True, null=True)),
                ('PoliceBitisTarihi', models.DateTimeField(blank=True, null=True)),
                ('SigortaSirketiKodu', models.CharField(blank=True, max_length=10, null=True)),
                ('PoliceNo', models.CharField(blank=True, max_length=30, null=True)),
                ('YenilemeNo', models.CharField(blank=True, max_length=10, null=True)),
                ('ZeyilNo', models.CharField(blank=True, max_length=10, null=True)),
                ('ZeyilAdi', models.CharField(blank=True, max_length=255, null=True)),
                ('ZeyilKodu', models.CharField(blank=True, max_length=10, null=True)),
                ('ZeyilTanzimTarihi', models.DateTimeField(blank=True, null=True)),
                ('PoliceOnayTarihi', models.DateTimeField(blank=True, null=True)),
                ('ZeyilBaslangicTarihi', models.DateTimeField(blank=True, null=True)),
                ('ZeyilBitisTarihi', models.DateTimeField(blank=True, null=True)),
                ('AracTrafikKademe', models.CharField(blank=True, max_length=10, null=True)),
                ('AracKaskoKademe', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_tramer_policies', to='agency.agency')),
                ('asset_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_tramer_policies', to='database.assetcars')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_tramer_policies', to='database.customer')),
            ],
            options={
                'db_table': 'external_tramer_policy',
                'unique_together': {('agency', 'PoliceNo', 'YenilemeNo', 'ZeyilNo')},
            },
        ),
    ]
