# Generated by Django 4.1.13 on 2025-07-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0086_externaltramerpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcars',
            name='external_policy',
            field=models.ForeignKey(blank=True, help_text="Tramer'den gelen dış poliçeyle ilişki", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_assets', to='database.externaltramerpolicy'),
        ),
    ]
