# Generated by Django 4.1.13 on 2025-07-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0087_assetcars_external_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcars',
            name='external_policy',
        ),
    ]
