# Generated by Django 4.1.13 on 2025-07-28 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0088_remove_assetcars_external_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltramerpolicy',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_tramer_policies', to='database.policybranch'),
        ),
    ]
