# Generated by Django 4.1.13 on 2025-07-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0089_externaltramerpolicy_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltramerpolicy',
            name='IptalMi',
            field=models.BooleanField(default=False),
        ),
    ]
