# Generated by Django 4.1.13 on 2025-07-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_agencypasswords_kaynak_kod_agencypasswords_sube_kod'),
        ('database', '0090_externaltramerpolicy_iptalmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('fail', 'Hatalı')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('auto', 'Zamanlı'), ('manual', 'Elle')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Cookie Log',
                'verbose_name_plural': 'Cookie Logları',
                'db_table': 'cookie_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
