# Generated by Django 5.1.7 on 2025-03-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('insurance_companies', models.ManyToManyField(blank=True, related_name='agency_insurance_companies', to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Acente',
                'verbose_name_plural': 'Acenteler',
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('branch_type', models.CharField(choices=[('own', 'Own Branch'), ('partner', 'Partner Branch')], default='own', max_length=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agency.agency')),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
                'db_table': 'agencybranch',
            },
        ),
        migrations.CreateModel(
            name='AgencyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_company_agencies', to='agency.agency')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_company_companies', to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Acente-Şirket İlişkisi',
                'verbose_name_plural': 'Acente-Şirket İlişkileri',
                'db_table': 'agencycompany',
                'unique_together': {('agency', 'company')},
            },
        ),
        migrations.CreateModel(
            name='AgencyPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('partaj_code', models.CharField(blank=True, max_length=255, null=True)),
                ('web_username', models.CharField(blank=True, max_length=255, null=True)),
                ('web_password', models.CharField(blank=True, max_length=255, null=True)),
                ('cookie', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='agency.agency')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='database.insurancecompany')),
            ],
            options={
                'verbose_name': 'Acente Şifre Bilgisi',
                'verbose_name_plural': 'Acente Şifre Bilgileri',
                'db_table': 'agencypasswords',
                'unique_together': {('agency', 'insurance_company')},
            },
        ),
    ]
