# Generated by Django 5.1.7 on 2025-03-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('database', '0002_alter_serviceconfiguration_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyServiceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_services', to='agency.agency')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_agencies', to='database.serviceconfiguration')),
            ],
            options={
                'verbose_name': 'Yetkilendirilmiş Servis',
                'verbose_name_plural': 'Yetkilendirilmiş Servisler',
                'db_table': 'agencyserviceauthorization',
                'unique_together': {('agency', 'service')},
            },
        ),
    ]
