# Generated by Django 4.1.13 on 2025-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agencyserviceauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyserviceauthorization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
