# Generated by Django 4.1.13 on 2025-05-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_offerserviceconfiguration'),
        ('agency', '0003_agencyserviceauthorization_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyOfferServiceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_offer_services', to='agency.agency')),
                ('offer_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_agencies', to='database.offerserviceconfiguration')),
            ],
            options={
                'verbose_name': 'Yetkilendirilmiş Teklif Servisi',
                'verbose_name_plural': 'Yetkilendirilmiş Teklif Servisleri',
                'db_table': 'agencyofferserviceauthorization',
                'unique_together': {('agency', 'offer_service')},
            },
        ),
    ]
