# Generated by Django 4.1.13 on 2025-06-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_agencyofferserviceauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypasswords',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
