# Generated by Django 4.1.13 on 2025-06-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_agencypasswords_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agencycompany',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agencyofferserviceauthorization',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agencypasswords',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agencyserviceauthorization',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
