# Generated by Django 4.1.13 on 2025-06-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_transferserviceconfiguration'),
        ('agency', '0006_alter_agency_id_alter_agencycompany_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyTransferServiceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('transfer_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.transferserviceconfiguration')),
            ],
            options={
                'unique_together': {('agency', 'transfer_service')},
            },
        ),
    ]
