# Generated by Django 4.1.13 on 2025-06-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_agencytransferserviceauthorization'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencytransferserviceauthorization',
            table='agencytransferserviceauthorization',
        ),
    ]
