# Generated by Django 4.1.13 on 2025-07-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_agencytransferserviceauthorization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypasswords',
            name='appSecurityKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencypasswords',
            name='authenticationKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencypasswords',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencypasswords',
            name='secret_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencypasswords',
            name='token_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencypasswords',
            name='token_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
