# Generated by Django 4.1.13 on 2025-07-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_agencypasswords_appsecuritykey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypasswords',
            name='authenticationKey',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
