# Generated by Django 4.1.13 on 2025-07-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_alter_agencypasswords_authenticationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypasswords',
            name='authenticationKey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
