# Generated by Django 4.1.13 on 2025-07-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_alter_agencypasswords_authenticationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypasswords',
            name='token_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
