# Generated by Django 4.1.13 on 2025-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_agencypasswords_token_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypasswords',
            name='kaynak_kod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agencypasswords',
            name='sube_kod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
